# version: '3.8'

services:
  react:
    build: .
    container_name: deukgeun-front-container
    ports:
      - "3333:80"
    volumes:
      - C:\\Users\\deukgeun2\\deploy\\git\\dg-multicampus-final-project\\front\\deukgeun\\public\\images:/usr/share/nginx/html/images
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/letsencrypt:/etc/letsencrypt
      # - ./data/www:/usr/share/nginx/html
      - ./data/www:/usr/share/nginx/html/.well-known/acme-challenge
      - ./build:/usr/share/nginx/html
    environment:
      - UPLOAD_PATH=/usr/share/nginx/html/images
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "30115:30115"
    volumes:
      - C:\\Users\\deukgeun2\\deploy\\git\\dg-multicampus-final-project\\front\\deukgeun\\public\\images:/usr/share/nginx/html/images
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/www:/usr/share/nginx/html
      - ./data/www:/usr/share/nginx/html/.well-known/acme-challenge
      - ./build:/usr/share/nginx/html
    depends_on:
      - react

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/var/lib/letsencrypt:/var/lib/letsencrypt
      # - ./data/www:/usr/share/nginx/html
      - ./data/www:/usr/share/nginx/html/.well-known/acme-challenge
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email jngwk.ch@gmail.com --agree-tos --no-eff-email -d deukgeun.site
