spring:
  application:
    name: deukgeun
  datasource:
    url: jdbc:mysql://localhost:3306/dgdb
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
  mvc:
    cors:
      allowed-origins: "*"
    # view:
    #   prefix: "/WEB-INF/views/"
    #   suffix: ".jsp"
    #   # jsp를 구동하기위해 추가
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./images/

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    # html구동하기위해 추가

com:
  conan:
    upload:
      path: images

server:
  port: 30000

# rabbitmq 값을 dynamic하게 사용하기 위한 값
rabbitmq:
  queue:
    name: dgQueue
    json:
      name: dqJsonQueue
  exchange:
    name: dgExchange
  routing:
    key: chat.#
    json:
      key: dgRoutingJsonKey

#시큐리티 보안키
security:
  jwt:
    secret-key: your-very-long-secret-key-of-at-least-32-characters

#로깅 디버그
logging:
  level:
    org:
    springframework:
      security: DEBUG
# email 관련
mail:
  host: smtp.gmail.com
  port: 587
  username: jngwk.ch@gmail.com
  password: lnzxrqgqsjqvdide
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
iamport:
  key: 7383144861344372
  secret: JbLmUseDFSoqpSadCWEGVwXv8BGwiduXEZ4CQwp3b8FuxjA66clAEv28uAN8wE3dRkIKZl8rJM7bNh7z

upload:
  path: C:\\Users\\deukgeun2\\deploy\\git\\dg-multicampus-final-project\\front\\deukgeun\\public\\images

admin:
  email: jngwk.ch@gmail.com
